# Permalinks
permalink:           pretty

# Setup
title:               Hyun Uk Chae
tagline:             PH.D. Student at University of Southern California
url:                 https://semiconguy.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Hyun Uk Chae
  url:               https://twitter.com/semiconguy
  email:             hyunukch@usc.edu

# Custom vars
version:             2.0.1
github:
  repo:              
google_analytics:    
twitter:             semiconguy
github:              
linkedin:            hyun-uk-chae-745738146

# Gems
plugins:
  # - jekyll-paginate
  # - jekyll-gist
